2023-06-12 20:01:08,575 INFO    MainThread:654 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-12 20:01:08,576 INFO    MainThread:654 [wandb_setup.py:_flush():76] Configure stats pid to 654
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Loading settings from /content/wandb/settings
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-12 20:01:08,577 INFO    MainThread:654 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-12 20:01:08,578 INFO    MainThread:654 [wandb_init.py:_log_setup():507] Logging user logs to /content/drive/MyDrive/VP_CrossPoint_2023/Pointnet2_PyTorch/pointnet2_ops_lib/wandb/run-20230612_200108-vj0xzs5i/logs/debug.log
2023-06-12 20:01:08,578 INFO    MainThread:654 [wandb_init.py:_log_setup():508] Logging internal logs to /content/drive/MyDrive/VP_CrossPoint_2023/Pointnet2_PyTorch/pointnet2_ops_lib/wandb/run-20230612_200108-vj0xzs5i/logs/debug-internal.log
2023-06-12 20:01:08,579 INFO    MainThread:654 [wandb_init.py:init():547] calling init triggers
2023-06-12 20:01:08,579 INFO    MainThread:654 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-12 20:01:08,579 INFO    MainThread:654 [wandb_init.py:init():596] starting backend
2023-06-12 20:01:08,579 INFO    MainThread:654 [wandb_init.py:init():600] setting up manager
2023-06-12 20:01:08,650 ERROR   MainThread:654 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
